package io.github.moehreag.dtaplot.socket.tcp;

import java.util.List;

public class Parameters extends DataVector {

	public Parameters() {
		super(List.of(
				unknown("ID_Transfert_LuxNet"),
				celsius("ID_Einst_WK_akt", true),
				celsius("ID_Einst_BWS_akt", true),
				heatingMode("ID_Ba_Hz_akt", true),
				hotWaterMode("ID_Ba_Bw_akt", true),
				unknown("ID_Ba_Al_akt"),
				unknown("ID_SU_FrkdHz"),
				unknown("ID_SU_FrkdBw"),
				unknown("ID_SU_FrkdAl"),
				unknown("ID_Einst_HReg_akt"),
				unknown("ID_Einst_HzHwMAt_akt"),
				celsius("ID_Einst_HzHwHKE_akt", true),
				celsius("ID_Einst_HzHKRANH_akt", true),
				celsius("ID_Einst_HzHKRABS_akt", true),
				celsius("ID_Einst_HzMK1E_akt", true),
				celsius("ID_Einst_HzMK1ANH_akt", true),
				celsius("ID_Einst_HzMK1ABS_akt", true),
				unknown("ID_Einst_HzFtRl_akt"),
				unknown("ID_Einst_HzFtMK1Vl_akt"),
				unknown("ID_Einst_SUBW_akt"),
				unknown("ID_Einst_BwTDI_akt_MO"),
				unknown("ID_Einst_BwTDI_akt_DI"),
				unknown("ID_Einst_BwTDI_akt_MI"),
				unknown("ID_Einst_BwTDI_akt_DO"),
				unknown("ID_Einst_BwTDI_akt_FR"),
				unknown("ID_Einst_BwTDI_akt_SA"),
				unknown("ID_Einst_BwTDI_akt_SO"),
				unknown("ID_Einst_BwTDI_akt_AL"),
				unknown("ID_Einst_AnlKonf_akt"),
				unknown("ID_Einst_Sprache_akt"),
				unknown("ID_Switchoff_Zahler"),
				unknown("ID_Switchoff_index"),
				unknown("ID_Einst_EvuTyp_akt"),
				unknown("ID_Einst_RFVEinb_akt"),
				unknown("ID_Einst_AbtZykMax_akt"),
				unknown("ID_Einst_HREinb_akt"),
				unknown("ID_Einst_ZWE1Art_akt"),
				unknown("ID_Einst_ZWE1Fkt_akt"),
				unknown("ID_Einst_ZWE2Art_akt"),
				unknown("ID_Einst_ZWE2Fkt_akt"),
				unknown("ID_Einst_BWBer_akt"),
				unknown("ID_Einst_En_Inst"),
				unknown("ID_Einst_MK1Typ_akt"),
				unknown("ID_Einst_ABTLuft_akt"),
				unknown("ID_Einst_TLAbt_akt"),
				unknown("ID_Einst_LAbtTime_akt"),
				unknown("ID_Einst_ASDTyp_akt"),
				celsius("ID_Einst_LGST_akt", true),
				unknown("ID_Einst_BwWpTime_akt"),
				unknown("ID_Einst_Popt_akt"),
				unknown("ID_Einst_Kurzprog_akt"),
				unknown("ID_Timer_Kurzprog_akt"),
				unknown("ID_Einst_ManAbt_akt"),
				unknown("ID_Einst_Ahz_akt"),
				unknown("ID_Einst_TVL_Ahz_1"),
				unknown("ID_Einst_TVL_Ahz_2"),
				unknown("ID_Einst_TVL_Ahz_3"),
				unknown("ID_Einst_TVL_Ahz_4"),
				unknown("ID_Einst_TVL_Ahz_5"),
				unknown("ID_Einst_TVL_Ahz_6"),
				unknown("ID_Einst_TVL_Ahz_7"),
				unknown("ID_Einst_TVL_Ahz_8"),
				unknown("ID_Einst_TVL_Ahz_9"),
				unknown("ID_Einst_TVL_Ahz_10"),
				unknown("ID_Einst_TVL_Std_1"),
				unknown("ID_Einst_TVL_Std_2"),
				unknown("ID_Einst_TVL_Std_3"),
				unknown("ID_Einst_TVL_Std_4"),
				unknown("ID_Einst_TVL_Std_5"),
				unknown("ID_Einst_TVL_Std_6"),
				unknown("ID_Einst_TVL_Std_7"),
				unknown("ID_Einst_TVL_Std_8"),
				unknown("ID_Einst_TVL_Std_9"),
				unknown("ID_Einst_TVL_Std_10"),
				kelvin("ID_Einst_BWS_Hyst_akt", true),
				unknown("ID_Temp_TBW_BwHD_saved"),
				unknown("ID_Einst_ABT1_akt"),
				unknown("ID_Einst_LABTpaus_akt"),
				unknown("ID_AHZ_state_akt"),
				celsius("ID_Sollwert_TRL_HZ_AHZ", true),
				unknown("ID_AHP_valid_records"),
				unknown("ID_Timer_AHZ_akt"),
				unknown("ID_Einst_BWTINP_akt"),
				unknown("ID_Einst_ZUPTYP_akt"),
				unknown("ID_Sollwert_TLG_max"),
				unknown("ID_Einst_BWZIP_akt"),
				unknown("ID_Einst_ERRmZWE_akt"),
				unknown("ID_Einst_TRBegr_akt"),
				kelvin("ID_Einst_HRHyst_akt", true),
				kelvin("ID_Einst_TRErhmax_akt", true),
				celsius("ID_Einst_ZWEFreig_akt", true),
				unknown("ID_Einst_TAmax_akt"),
				unknown("ID_Einst_TAmin_akt"),
				unknown("ID_Einst_TWQmin_akt"),
				unknown("ID_Einst_THGmax_akt"),
				unknown("ID_Einst_FRGT2VD_akt"),
				unknown("ID_Einst_TV2VDBW_akt"),
				unknown("ID_Einst_SuAll_akt"),
				unknown("ID_Einst_TAbtEnd_akt"),
				unknown("ID_Einst_NrKlingel_akt"),
				unknown("ID_Einst_BWStyp_akt"),
				unknown("ID_Einst_ABT2_akt"),
				unknown("ID_Einst_UeVd_akt"),
				unknown("ID_Einst_RTyp_akt"),
				unknown("ID_Einst_AhpM_akt"),
				celsius("ID_Soll_BWS_akt", true),
				unknown("ID_Timer_Password"),
				accessLevel("ID_Einst_Zugangscode", true),
				coolingMode("ID_Einst_BA_Kuehl_akt", true),
				unknown("ID_Sollwert_Kuehl1_akt"),
				celsius("ID_Einst_KuehlFreig_akt", true),
				celsius("ID_Einst_TAbsMin_akt", true),
				unknown("ID_TWQmin_saved"),
				unknown("ID_CWP_saved"),
				unknown("ID_Einst_Anode_akt"),
				unknown("ID_Timer_pexoff_akt"),
				unknown("ID_Einst_AnlPrio_Hzakt"),
				unknown("ID_Einst_AnlPrio_Bwakt"),
				unknown("ID_Einst_AnlPrio_Swakt"),
				poolMode("ID_Ba_Sw_akt", true),
				unknown("ID_Einst_RTypMK1_akt"),
				unknown("ID_Einst_RTypMK2_akt"),
				kelvin("ID_Einst_TDC_Ein_akt"),
				kelvin("ID_Einst_TDC_Aus_akt"),
				celsius("ID_Einst_TDC_Max_akt", true),
				unknown("ID_Einst_HysHzExEn_akt"),
				unknown("ID_Einst_HysBwExEn_akt"),
				unknown("ID_Einst_ZWE3Art_akt"),
				unknown("ID_Einst_ZWE3Fkt_akt"),
				unknown("ID_Einst_HzSup_akt"),
				unknown("ID_Einst_MK2Typ_akt"),
				unknown("ID_Einst_KuTyp_akt"),
				celsius("ID_Sollwert_KuCft1_akt", true),
				celsius("ID_Sollwert_KuCft2_akt", true),
				celsius("ID_Sollwert_AtDif1_akt", true),
				celsius("ID_Sollwert_AtDif2_akt", true),
				unknown("ID_SU_FrkdSwb"),
				unknown("ID_Einst_SwbBer_akt"),
				unknown("ID_Einst_TV2VDSWB_akt"),
				unknown("ID_Einst_MinSwan_Time_akt"),
				unknown("ID_Einst_SuMk2_akt"),
				celsius("ID_Einst_HzMK2E_akt", true),
				celsius("ID_Einst_HzMK2ANH_akt", true),
				celsius("ID_Einst_HzMK2ABS_akt", true),
				unknown("ID_Einst_HzMK2Hgr_akt"),
				unknown("ID_Einst_HzFtMK2Vl_akt"),
				unknown("ID_Temp_THG_BwHD_saved"),
				unknown("ID_Temp_TA_BwHD_saved"),
				unknown("ID_Einst_BwHup_akt"),
				unknown("ID_Einst_TVLmax_akt"),
				unknown("ID_Einst_MK1LzFaktor_akt"),
				unknown("ID_Einst_MK2LzFaktor_akt"),
				unknown("ID_Einst_MK1PerFaktor_akt"),
				unknown("ID_Einst_MK2PerFaktor_akt"),
				unknown("ID_Entl_Zyklus_akt"),
				unknown("ID_Einst_Entl_time_akt"),
				unknown("ID_Entl_Pause"),
				unknown("ID_Entl_timer"),
				unknown("ID_Einst_Entl_akt"),
				unknown("ID_Ahz_HLeist_confirmed"),
				unknown("ID_FirstInit_akt"),
				unknown("ID_Einst_SuAll_akt2"),
				unknown("ID_Einst_SuAllWo_zeit_0_0"),
				unknown("ID_Einst_SuAllWo_zeit_0_1"),
				unknown("ID_Einst_SuAllWo_zeit_1_0"),
				unknown("ID_Einst_SuAllWo_zeit_1_1"),
				unknown("ID_Einst_SuAllWo_zeit_2_0"),
				unknown("ID_Einst_SuAllWo_zeit_2_1"),
				unknown("ID_Einst_SuAll25_zeit_0_0"),
				unknown("ID_Einst_SuAll25_zeit_0_1"),
				unknown("ID_Einst_SuAll25_zeit_1_0"),
				unknown("ID_Einst_SuAll25_zeit_1_1"),
				unknown("ID_Einst_SuAll25_zeit_2_0"),
				unknown("ID_Einst_SuAll25_zeit_2_1"),
				unknown("ID_Einst_SuAll25_zeit_0_2"),
				unknown("ID_Einst_SuAll25_zeit_0_3"),
				unknown("ID_Einst_SuAll25_zeit_1_2"),
				unknown("ID_Einst_SuAll25_zeit_1_3"),
				unknown("ID_Einst_SuAll25_zeit_2_2"),
				unknown("ID_Einst_SuAll25_zeit_2_3"),
				unknown("ID_Einst_SuAllTg_zeit_0_0"),
				unknown("ID_Einst_SuAllTg_zeit_0_1"),
				unknown("ID_Einst_SuAllTg_zeit_1_0"),
				unknown("ID_Einst_SuAllTg_zeit_1_1"),
				unknown("ID_Einst_SuAllTg_zeit_2_0"),
				unknown("ID_Einst_SuAllTg_zeit_2_1"),
				unknown("ID_Einst_SuAllTg_zeit_0_2"),
				unknown("ID_Einst_SuAllTg_zeit_0_3"),
				unknown("ID_Einst_SuAllTg_zeit_1_2"),
				unknown("ID_Einst_SuAllTg_zeit_1_3"),
				unknown("ID_Einst_SuAllTg_zeit_2_2"),
				unknown("ID_Einst_SuAllTg_zeit_2_3"),
				unknown("ID_Einst_SuAllTg_zeit_0_4"),
				unknown("ID_Einst_SuAllTg_zeit_0_5"),
				unknown("ID_Einst_SuAllTg_zeit_1_4"),
				unknown("ID_Einst_SuAllTg_zeit_1_5"),
				unknown("ID_Einst_SuAllTg_zeit_2_4"),
				unknown("ID_Einst_SuAllTg_zeit_2_5"),
				unknown("ID_Einst_SuAllTg_zeit_0_6"),
				unknown("ID_Einst_SuAllTg_zeit_0_7"),
				unknown("ID_Einst_SuAllTg_zeit_1_6"),
				unknown("ID_Einst_SuAllTg_zeit_1_7"),
				unknown("ID_Einst_SuAllTg_zeit_2_6"),
				unknown("ID_Einst_SuAllTg_zeit_2_7"),
				unknown("ID_Einst_SuAllTg_zeit_0_8"),
				unknown("ID_Einst_SuAllTg_zeit_0_9"),
				unknown("ID_Einst_SuAllTg_zeit_1_8"),
				unknown("ID_Einst_SuAllTg_zeit_1_9"),
				unknown("ID_Einst_SuAllTg_zeit_2_8"),
				unknown("ID_Einst_SuAllTg_zeit_2_9"),
				unknown("ID_Einst_SuAllTg_zeit_0_10"),
				unknown("ID_Einst_SuAllTg_zeit_0_11"),
				unknown("ID_Einst_SuAllTg_zeit_1_10"),
				unknown("ID_Einst_SuAllTg_zeit_1_11"),
				unknown("ID_Einst_SuAllTg_zeit_2_10"),
				unknown("ID_Einst_SuAllTg_zeit_2_11"),
				unknown("ID_Einst_SuAllTg_zeit_0_12"),
				unknown("ID_Einst_SuAllTg_zeit_0_13"),
				unknown("ID_Einst_SuAllTg_zeit_1_12"),
				unknown("ID_Einst_SuAllTg_zeit_1_13"),
				unknown("ID_Einst_SuAllTg_zeit_2_12"),
				unknown("ID_Einst_SuAllTg_zeit_2_13"),
				timerProgram("ID_Einst_SuHkr_akt", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_0_0", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_0_1", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_1_0", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_1_1", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_2_0", true),
				timeOfDay("ID_Einst_SuHkrW0_zeit_2_1", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_0_0", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_0_1", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_1_0", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_1_1", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_2_0", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_2_1", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_0_2", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_0_3", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_1_2", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_1_3", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_2_2", true),
				timeOfDay("ID_Einst_SuHkr25_zeit_2_3", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_0", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_1", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_0", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_1", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_0", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_1", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_2", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_3", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_2", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_3", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_2", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_3", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_4", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_5", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_4", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_5", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_4", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_5", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_6", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_7", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_6", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_7", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_6", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_7", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_8", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_9", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_8", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_9", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_8", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_9", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_10", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_11", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_10", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_11", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_10", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_11", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_12", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_0_13", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_12", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_1_13", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_12", true),
				timeOfDay("ID_Einst_SuHkrTG_zeit_2_13", true),
				timerProgram("ID_Einst_SuMk1_akt"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk1W0_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk125_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk125_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk125_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk125_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk125_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk125_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk125_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk125_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk125_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk125_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk125_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk125_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_4"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_5"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_4"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_5"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_4"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_5"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_6"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_7"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_6"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_7"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_6"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_7"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_8"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_9"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_8"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_9"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_8"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_9"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_10"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_11"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_10"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_11"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_10"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_11"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_12"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_0_13"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_12"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_1_13"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_12"),
				timeOfDay("ID_Einst_SuMk1TG_zeit_2_13"),
				timerProgram("ID_Einst_SuMk2_akt2"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk2Wo_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk225_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk225_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk225_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk225_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk225_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk225_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk225_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk225_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk225_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk225_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk225_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk225_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_4"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_5"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_4"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_5"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_4"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_5"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_6"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_7"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_6"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_7"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_6"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_7"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_8"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_9"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_8"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_9"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_8"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_9"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_10"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_11"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_10"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_11"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_10"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_11"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_12"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_0_13"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_12"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_1_13"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_12"),
				timeOfDay("ID_Einst_SuMk2Tg_zeit_2_13"),
				timerProgram("ID_Einst_SUBW_akt2", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_0_0", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_0_1", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_1_0", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_1_1", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_2_0", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_2_1", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_3_0", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_3_1", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_4_0", true),
				timeOfDay("ID_Einst_SuBwWO_zeit_4_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_0_0", true),
				timeOfDay("ID_Einst_SuBw25_zeit_0_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_1_0", true),
				timeOfDay("ID_Einst_SuBw25_zeit_1_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_2_0", true),
				timeOfDay("ID_Einst_SuBw25_zeit_2_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_3_0", true),
				timeOfDay("ID_Einst_SuBw25_zeit_3_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_4_0", true),
				timeOfDay("ID_Einst_SuBw25_zeit_4_1", true),
				timeOfDay("ID_Einst_SuBw25_zeit_0_2", true),
				timeOfDay("ID_Einst_SuBw25_zeit_0_3", true),
				timeOfDay("ID_Einst_SuBw25_zeit_1_2", true),
				timeOfDay("ID_Einst_SuBw25_zeit_1_3", true),
				timeOfDay("ID_Einst_SuBw25_zeit_2_2", true),
				timeOfDay("ID_Einst_SuBw25_zeit_2_3", true),
				timeOfDay("ID_Einst_SuBw25_zeit_3_2", true),
				timeOfDay("ID_Einst_SuBw25_zeit_3_3", true),
				timeOfDay("ID_Einst_SuBw25_zeit_4_2", true),
				timeOfDay("ID_Einst_SuBw25_zeit_4_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_0", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_1", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_0", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_1", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_0", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_1", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_0", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_1", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_0", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_1", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_2", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_2", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_2", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_2", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_2", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_3", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_4", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_5", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_4", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_5", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_4", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_5", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_4", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_5", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_4", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_5", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_6", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_7", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_6", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_7", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_6", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_7", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_6", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_7", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_6", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_7", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_8", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_9", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_8", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_9", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_8", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_9", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_8", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_9", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_8", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_9", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_10", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_11", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_10", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_11", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_10", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_11", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_10", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_11", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_10", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_11", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_12", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_0_13", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_12", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_1_13", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_12", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_2_13", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_12", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_3_13", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_12", true),
				timeOfDay("ID_Einst_SuBwTG_zeit_4_13", true),
				timerProgram("ID_Einst_SuZIP_akt", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_0_0", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_0_1", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_1_0", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_1_1", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_2_0", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_2_1", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_3_0", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_3_1", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_4_0", true),
				timeOfDay("ID_Einst_SuZIPWo_zeit_4_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_0_0", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_0_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_1_0", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_1_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_2_0", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_2_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_3_0", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_3_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_4_0", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_4_1", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_0_2", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_0_3", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_1_2", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_1_3", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_2_2", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_2_3", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_3_2", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_3_3", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_4_2", true),
				timeOfDay("ID_Einst_SuZIP25_zeit_4_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_0", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_1", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_0", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_1", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_0", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_1", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_0", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_1", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_0", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_1", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_2", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_2", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_2", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_2", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_2", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_3", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_4", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_5", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_4", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_5", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_4", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_5", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_4", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_5", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_4", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_5", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_6", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_7", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_6", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_7", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_6", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_7", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_6", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_7", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_6", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_7", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_8", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_9", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_8", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_9", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_8", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_9", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_8", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_9", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_8", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_9", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_10", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_11", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_10", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_11", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_10", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_11", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_10", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_11", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_10", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_11", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_12", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_0_13", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_12", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_1_13", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_12", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_2_13", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_12", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_3_13", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_12", true),
				timeOfDay("ID_Einst_SuZIPTg_zeit_4_13", true),
				timerProgram("ID_Einst_SuSwb_akt"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_0_0"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_0_1"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_1_0"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_1_1"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_2_0"),
				timeOfDay("ID_Einst_SuSwbWo_zeit_2_1"),
				timeOfDay("ID_Einst_SuSwb25_zeit_0_0"),
				timeOfDay("ID_Einst_SuSwb25_zeit_0_1"),
				timeOfDay("ID_Einst_SuSwb25_zeit_1_0"),
				timeOfDay("ID_Einst_SuSwb25_zeit_1_1"),
				timeOfDay("ID_Einst_SuSwb25_zeit_2_0"),
				timeOfDay("ID_Einst_SuSwb25_zeit_2_1"),
				timeOfDay("ID_Einst_SuSwb25_zeit_0_2"),
				timeOfDay("ID_Einst_SuSwb25_zeit_0_3"),
				timeOfDay("ID_Einst_SuSwb25_zeit_1_2"),
				timeOfDay("ID_Einst_SuSwb25_zeit_1_3"),
				timeOfDay("ID_Einst_SuSwb25_zeit_2_2"),
				timeOfDay("ID_Einst_SuSwb25_zeit_2_3"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_0"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_1"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_0"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_1"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_0"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_1"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_2"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_3"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_2"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_3"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_2"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_3"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_4"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_5"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_4"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_5"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_4"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_5"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_6"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_7"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_6"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_7"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_6"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_7"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_8"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_9"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_8"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_9"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_8"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_9"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_10"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_11"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_10"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_11"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_10"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_11"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_12"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_0_13"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_12"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_1_13"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_12"),
				timeOfDay("ID_Einst_SuSwbTg_zeit_2_13"),
				seconds("ID_Zaehler_BetrZeitWP"),
				seconds("ID_Zaehler_BetrZeitVD1"),
				seconds("ID_Zaehler_BetrZeitVD2"),
				seconds("ID_Zaehler_BetrZeitZWE1"),
				seconds("ID_Zaehler_BetrZeitZWE2"),
				seconds("ID_Zaehler_BetrZeitZWE3"),
				count("ID_Zaehler_BetrZeitImpVD1"),
				count("ID_Zaehler_BetrZeitImpVD2"),
				unknown("ID_Zaehler_BetrZeitEZMVD1"),
				unknown("ID_Zaehler_BetrZeitEZMVD2"),
				unknown("ID_Einst_Entl_Typ_0"),
				unknown("ID_Einst_Entl_Typ_1"),
				unknown("ID_Einst_Entl_Typ_2"),
				unknown("ID_Einst_Entl_Typ_3"),
				unknown("ID_Einst_Entl_Typ_4"),
				unknown("ID_Einst_Entl_Typ_5"),
				unknown("ID_Einst_Entl_Typ_6"),
				unknown("ID_Einst_Entl_Typ_7"),
				unknown("ID_Einst_Entl_Typ_8"),
				unknown("ID_Einst_Entl_Typ_9"),
				unknown("ID_Einst_Entl_Typ_10"),
				unknown("ID_Einst_Entl_Typ_11"),
				unknown("ID_Einst_Entl_Typ_12"),
				unknown("ID_Einst_Vorl_max_MK1"),
				unknown("ID_Einst_Vorl_max_MK2"),
				unknown("ID_SU_FrkdMK1"),
				unknown("ID_SU_FrkdMK2"),
				mixedCircuitMode("ID_Ba_Hz_MK1_akt"),
				mixedCircuitMode("ID_Ba_Hz_MK2_akt"),
				unknown("ID_Einst_Zirk_Ein_akt"),
				unknown("ID_Einst_Zirk_Aus_akt"),
				unknown("ID_Einst_Heizgrenze"),
				celsius("ID_Einst_Heizgrenze_Temp"),
				unknown("ID_VariablenIBNgespeichert"),
				unknown("ID_SchonIBNAssistant"),
				unknown("ID_Heizgrenze_0"),
				unknown("ID_Heizgrenze_1"),
				unknown("ID_Heizgrenze_2"),
				unknown("ID_Heizgrenze_3"),
				unknown("ID_Heizgrenze_4"),
				unknown("ID_Heizgrenze_5"),
				unknown("ID_Heizgrenze_6"),
				unknown("ID_Heizgrenze_7"),
				unknown("ID_Heizgrenze_8"),
				unknown("ID_Heizgrenze_9"),
				unknown("ID_Heizgrenze_10"),
				unknown("ID_Heizgrenze_11"),
				unknown("ID_SchemenIBNgewahlt"),
				unknown("ID_Switchoff_file_0_0"),
				unknown("ID_Switchoff_file_1_0"),
				unknown("ID_Switchoff_file_2_0"),
				unknown("ID_Switchoff_file_3_0"),
				unknown("ID_Switchoff_file_4_0"),
				unknown("ID_Switchoff_file_0_1"),
				unknown("ID_Switchoff_file_1_1"),
				unknown("ID_Switchoff_file_2_1"),
				unknown("ID_Switchoff_file_3_1"),
				unknown("ID_Switchoff_file_4_1"),
				unknown("ID_DauerDatenLoggerAktiv"),
				unknown("ID_Laufvar_Heizgrenze"),
				seconds("ID_Zaehler_BetrZeitHz"),
				seconds("ID_Zaehler_BetrZeitBW"),
				seconds("ID_Zaehler_BetrZeitKue"),
				unknown("ID_SU_FstdHz"),
				unknown("ID_SU_FstdBw"),
				unknown("ID_SU_FstdSwb"),
				unknown("ID_SU_FstdMK1"),
				unknown("ID_SU_FstdMK2"),
				unknown("ID_FerienAbsenkungHz"),
				unknown("ID_FerienAbsenkungMK1"),
				unknown("ID_FerienAbsenkungMK2"),
				unknown("ID_FerienModusAktivHz"),
				unknown("ID_FerienModusAktivBw"),
				unknown("ID_FerienModusAktivSwb"),
				unknown("ID_FerienModusAktivMk1"),
				unknown("ID_FerienModusAktivMk2"),
				unknown("ID_DisplayContrast_akt"),
				unknown("ID_Ba_Hz_saved"),
				unknown("ID_Ba_Bw_saved"),
				unknown("ID_Ba_Sw_saved"),
				unknown("ID_Ba_Hz_MK1_saved"),
				unknown("ID_Ba_Hz_MK2_saved"),
				unknown("ID_AdresseIP_akt"),
				unknown("ID_SubNetMask_akt"),
				unknown("ID_Add_Broadcast_akt"),
				unknown("ID_Add_StdGateway_akt"),
				unknown("ID_DHCPServerAktiv_akt"),
				unknown("ID_WebserverPasswort_1_akt"),
				unknown("ID_WebserverPasswort_2_akt"),
				unknown("ID_WebserverPasswort_3_akt"),
				unknown("ID_WebserverPasswort_4_akt"),
				unknown("ID_WebserverPasswort_5_akt"),
				unknown("ID_WebserverPasswort_6_akt"),
				unknown("ID_WebServerWerteBekommen"),
				unknown("ID_Einst_ParBetr_akt"),
				unknown("ID_Einst_WpAnz_akt"),
				unknown("ID_Einst_PhrTime_akt"),
				unknown("ID_Einst_HysPar_akt"),
				unknown("ID_IP_PB_Slave_0"),
				unknown("ID_IP_PB_Slave_1"),
				unknown("ID_IP_PB_Slave_2"),
				unknown("ID_IP_PB_Slave_3"),
				unknown("ID_IP_PB_Slave_4"),
				unknown("ID_IP_PB_Slave_5"),
				unknown("ID_Einst_BwHup_akt_backup"),
				unknown("ID_Einst_SuMk3_akt"),
				celsius("ID_Einst_HzMK3E_akt", true),
				celsius("ID_Einst_HzMK3ANH_akt", true),
				celsius("ID_Einst_HzMK3ABS_akt", true),
				unknown("ID_Einst_HzMK3Hgr_akt"),
				unknown("ID_Einst_HzFtMK3Vl_akt"),
				mixedCircuitMode("ID_Ba_Hz_MK3_akt", true),
				unknown("ID_Einst_MK3Typ_akt"),
				unknown("ID_Einst_RTypMK3_akt"),
				unknown("ID_Einst_MK3LzFaktor_akt"),
				unknown("ID_Einst_MK3PerFaktor_akt"),
				unknown("ID_FerienModusAktivMk3"),
				unknown("ID_SU_FrkdMK3"),
				unknown("ID_FerienAbsenkungMK3"),
				unknown("ID_SU_FstdMK3"),
				timerProgram("ID_Einst_SuMk3_akt2"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk3Wo_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk325_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk325_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk325_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk325_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk325_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk325_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk325_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk325_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk325_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk325_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk325_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk325_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_0"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_1"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_0"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_1"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_0"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_1"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_2"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_3"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_2"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_3"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_2"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_3"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_4"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_5"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_4"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_5"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_4"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_5"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_6"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_7"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_6"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_7"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_6"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_7"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_8"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_9"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_8"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_9"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_8"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_9"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_10"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_11"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_10"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_11"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_10"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_11"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_12"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_0_13"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_12"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_1_13"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_12"),
				timeOfDay("ID_Einst_SuMk3Tg_zeit_2_13"),
				unknown("ID_Ba_Hz_MK3_saved"),
				hours("ID_Einst_Kuhl_Zeit_Ein_akt", true),
				hours("ID_Einst_Kuhl_Zeit_Aus_akt", true),
				energy("ID_Waermemenge_Seit"),
				unknown("ID_Waermemenge_WQ"),
				energy("ID_Waermemenge_Hz"),
				unknown("ID_Waermemenge_WQ_ges"),
				unknown("ID_Einst_Entl_Typ_13"),
				unknown("ID_Einst_Entl_Typ_14"),
				unknown("ID_Einst_Entl_Typ_15"),
				seconds("ID_Zaehler_BetrZeitSW"),
				unknown("ID_Einst_Fernwartung_akt"),
				unknown("ID_AdresseIPServ_akt"),
				unknown("ID_Einst_TA_EG_akt"),
				unknown("ID_Einst_TVLmax_EG_akt"),
				minutes("ID_Einst_Popt_Nachlauf_akt", true),
				unknown("ID_FernwartungVertrag_akt"),
				unknown("ID_FernwartungAktuZeit"),
				unknown("ID_Einst_Effizienzpumpe_Nominal_akt"),
				unknown("ID_Einst_Effizienzpumpe_Minimal_akt"),
				unknown("ID_Einst_Effizienzpumpe_akt"),
				unknown("ID_Einst_Waermemenge_akt"),
				unknown("ID_Einst_Wm_Versorgung_Korrektur_akt"),
				unknown("ID_Einst_Wm_Auswertung_Korrektur_akt"),
				unknown("ID_SoftwareUpdateJetztGemacht_akt"),
				unknown("ID_WP_SerienNummer_DATUM"),
				unknown("ID_WP_SerienNummer_HEX"),
				unknown("ID_WP_SerienNummer_INDEX"),
				unknown("ID_ProgWerteWebSrvBeobarten"),
				energy("ID_Waermemenge_BW"),
				energy("ID_Waermemenge_SW"),
				timestamp("ID_Waermemenge_Datum"),
				solarMode("ID_Einst_Solar_akt", true),
				unknown("ID_BSTD_Solar"),
				celsius("ID_Einst_TDC_Koll_Max_akt"),
				unknown("ID_Einst_Akt_Kuehlung_akt"),
				unknown("ID_Einst_Vorlauf_VBO_akt"),
				unknown("ID_Einst_KRHyst_akt"),
				unknown("ID_Einst_Akt_Kuehl_Speicher_min_akt"),
				unknown("ID_Einst_Akt_Kuehl_Freig_WQE_akt"),
				unknown("ID_NDAB_WW_Anzahl"),
				unknown("ID_NDS_WW_KD_Quitt"),
				unknown("ID_Einst_AbtZykMin_akt"),
				unknown("ID_Einst_VD2_Zeit_Min_akt"),
				unknown("ID_Einst_Hysterese_HR_verkuerzt_akt"),
				ventilationMode("ID_Einst_BA_Lueftung_akt", true),
				timerProgram("ID_Einst_SuLuf_akt"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_0_0_0"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_0_1_0"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_0_2_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_0_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_1_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_2_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_0_2"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_1_2"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_0_2_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_0_12"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_1_12"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_0_2_12"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_1_0_0"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_1_1_0"),
				timeOfDay2("ID_Einst_SuLufWo_zeit_1_2_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_0_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_1_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_2_0"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_0_2"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_1_2"),
				timeOfDay2("ID_Einst_SuLuf25_zeit_1_2_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_0"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_2"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_4"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_6"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_8"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_10"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_0_12"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_1_12"),
				timeOfDay2("ID_Einst_SuLufTg_zeit_1_2_12"),
				unknown("ID_FerienModusAktivLueftung"),
				unknown("ID_Einst_BA_Lueftung_saved"),
				unknown("ID_SU_FrkdLueftung"),
				unknown("ID_SU_FstdLueftung"),
				unknown("ID_Einst_Luf_Feuchteschutz_akt"),
				unknown("ID_Einst_Luf_Reduziert_akt"),
				unknown("ID_Einst_Luf_Nennlueftung_akt"),
				unknown("ID_Einst_Luf_Intensivlueftung_akt"),
				unknown("ID_Timer_Fil_4Makt"),
				unknown("ID_Timer_Fil_WoAkt"),
				celsius("ID_Sollwert_KuCft3_akt", true),
				celsius("ID_Sollwert_AtDif3_akt", true),
				unknown("ID_Bitmaske_0"),
				unknown("ID_Einst_Lueftungsstufen"),
				unknown("ID_SysEin_Meldung_TDI"),
				unknown("ID_SysEin_Typ_WZW"),
				unknown("ID_Einst_GLT_aktiviert"),
				unknown("ID_Einst_BW_max"),
				unknown("ID_Einst_Sollwert_TRL_Kuehlen"),
				unknown("ID_Einst_Medium_Waermequelle"),
				unknown("ID_Einst_Photovoltaik_akt"),
				unknown("ID_Einst_Multispeicher_akt"),
				unknown("ID_Einst_PKuehlTime_akt"),
				celsius("ID_Einst_Minimale_Ruecklaufsolltemperatur", true),
				unknown("ID_RBE_Einflussfaktor_RT_akt"),
				unknown("ID_RBE_Freigabe_Kuehlung_akt"),
				unknown("ID_RBE_Waermeverteilsystem_akt"),
				unknown("ID_RBE_Zeit_Heizstab_aktiv"),
				unknown("ID_SEC_ND_Alarmgrenze"),
				unknown("ID_SEC_HD_Alarmgrenze"),
				unknown("ID_SEC_Abtauendtemperatur"),
				unknown("ID_Einst_Min_RPM_BW"),
				unknown("ID_Einst_Luf_Feuchteschutz_Faktor_akt"),
				unknown("ID_Einst_Luf_Reduziert_Faktor_akt"),
				unknown("ID_Einst_Luf_Nennlueftung_Faktor_akt"),
				unknown("ID_Einst_Luf_Intensivlueftung_Faktor_akt"),
				minutes("ID_Einst_Freigabe_Zeit_ZWE", true),
				unknown("ID_Einst_min_VL_Kuehl"),
				bool("ID_Einst_Warmwasser_Nachheizung", true),
				unknown("ID_Switchoff_file_LWD2_0_0"),
				unknown("ID_Switchoff_file_LWD2_1_0"),
				unknown("ID_Switchoff_file_LWD2_2_0"),
				unknown("ID_Switchoff_file_LWD2_3_0"),
				unknown("ID_Switchoff_file_LWD2_4_0"),
				unknown("ID_Switchoff_file_LWD2_0_1"),
				unknown("ID_Switchoff_file_LWD2_1_1"),
				unknown("ID_Switchoff_file_LWD2_2_1"),
				unknown("ID_Switchoff_file_LWD2_3_1"),
				unknown("ID_Switchoff_file_LWD2_4_1"),
				unknown("ID_Switchoff_index_LWD2"),
				unknown("ID_Einst_Effizienzpumpe_Nominal_2"),
				unknown("ID_Einst_Effizienzpumpe_Minimal_2"),
				unknown("ID_Einst_Wm_Versorgung_Korrektur_2"),
				unknown("ID_Einst_Wm_Auswertung_Korrektur_2"),
				unknown("ID_Einst_isTwin"),
				unknown("ID_Einst_TAmin_2"),
				unknown("ID_Einst_TVLmax_2"),
				unknown("ID_Einst_TA_EG_2"),
				unknown("ID_Einst_TVLmax_EG_2"),
				unknown("ID_Waermemenge_Hz_2"),
				unknown("ID_Waermemenge_BW_2"),
				unknown("ID_Waermemenge_SW_2"),
				unknown("ID_Waermemenge_Seit_2"),
				unknown("ID_Einst_Entl_Typ_15_2"),
				hours2("ID_Einst_WW_Nachheizung_max", true),
				unknown("ID_Einst_Kuhl_Zeit_Ein_RT"),
				unknown("ID_Einst_ZWE1_Pos"),
				unknown("ID_Einst_ZWE2_Pos"),
				unknown("ID_Einst_ZWE3_Pos"),
				unknown("ID_Einst_Leistung_ZWE"),
				unknown("ID_WP_SN2_DATUM"),
				unknown("ID_WP_SN2_HEX"),
				unknown("ID_WP_SN2_INDEX"),
				unknown("ID_CWP_saved2"),
				unknown("ID_Einst_SmartGrid"),
				unknown("ID_Einst_P155_HDS"),
				unknown("ID_Einst_P155_PumpHeat_Max"),
				unknown("ID_Einst_P155_PumpHeatCtrl"),
				unknown("ID_Einst_P155_PumpDHWCtrl"),
				unknown("ID_Einst_P155_PumpDHW_RPM"),
				unknown("ID_Einst_P155_PumpPoolCtrl"),
				unknown("ID_Einst_P155_PumpPool_RPM"),
				unknown("ID_Einst_P155_PumpCool_RPM"),
				unknown("ID_Einst_P155_PumpVBOCtrl"),
				unknown("ID_Einst_P155_PumpVBO_RPM_C"),
				unknown("ID_Einst_P155_PumpDHW_Max"),
				unknown("ID_Einst_P155_PumpPool_Max"),
				unknown("ID_Einst_P155_Sperrband_1"),
				unknown("ID_Einst_P155_Leistungsfreigabe"),
				unknown("ID_Einst_P155_DHW_Freq"),
				unknown("ID_Einst_SWHUP"),
				unknown("ID_Einst_P155_SWB_Freq"),
				unknown("ID_Einst_MK1_Regelung"),
				unknown("ID_Einst_MK2_Regelung"),
				unknown("ID_Einst_MK3_Regelung"),
				unknown("ID_Einst_PV_WW_Sperrzeit"),
				unknown("ID_Einst_Warmwasser_extra"),
				unknown("ID_Einst_Vorl_akt_Kuehl"),
				unknown("ID_WP_SN3_DATUM"),
				unknown("ID_WP_SN3_HEX"),
				unknown("ID_WP_SN3_INDEX"),
				unknown("ID_Einst_Vorlauf_ZUP"),
				unknown("ID_Einst_Abtauen_im_Warmwasser"),
				energy("ID_Waermemenge_ZWE"),
				energy("ID_Waermemenge_Reset"),
				unknown("ID_Waermemenge_Reset_2"),
				unknown("ID_Einst_Brunnenpumpe_min"),
				unknown("ID_Einst_Brunnenpumpe_max"),
				unknown("ID_Einst_SmartHomeID"),
				unknown("ID_Einst_SmartHK"),
				unknown("ID_Einst_SmartMK1"),
				unknown("ID_Einst_SmartMK2"),
				unknown("ID_Einst_SmartMK3"),
				unknown("ID_Einst_SmartWW"),
				unknown("ID_Einst_SmartDefrost"),
				unknown("ID_Einst_Empty1071"),
				unknown("ID_Einst_MinVLMK1"),
				unknown("ID_Einst_MinVLMK2"),
				unknown("ID_Einst_MinVLMK3"),
				unknown("ID_Einst_MaxVLMK1"),
				unknown("ID_Einst_MaxVLMK2"),
				unknown("ID_Einst_MaxVLMK3"),
				unknown("ID_Einst_SmartPlusHz"),
				unknown("ID_Einst_SmartMinusHz"),
				unknown("ID_Einst_SmartPlusMK1"),
				unknown("ID_Einst_SmartMinusMK1"),
				unknown("ID_Einst_SmartPlusMK2"),
				unknown("ID_Einst_SmartMinusMK2"),
				unknown("ID_Einst_SmartPlusMK3"),
				unknown("ID_Einst_SmartMinusMK3"),
				unknown("Unknown_Parameter_1086"),
				unknown("Unknown_Parameter_1087"),
				unknown("Unknown_Parameter_1088"),
				unknown("Unknown_Parameter_1089"),
				unknown("Unknown_Parameter_1090"),
				unknown("Unknown_Parameter_1091"),
				timerProgram("ID_Einst_SuSilence"),
				timeOfDay2("ID_Einst_SilenceTimer_0"),
				timeOfDay2("ID_Einst_SilenceTimer_1"),
				timeOfDay2("ID_Einst_SilenceTimer_2"),
				timeOfDay2("ID_Einst_SilenceTimer_3"),
				timeOfDay2("ID_Einst_SilenceTimer_4"),
				timeOfDay2("ID_Einst_SilenceTimer_5"),
				timeOfDay2("ID_Einst_SilenceTimer_6"),
				timeOfDay2("ID_Einst_SilenceTimer_7"),
				timeOfDay2("ID_Einst_SilenceTimer_8"),
				timeOfDay2("ID_Einst_SilenceTimer_9"),
				timeOfDay2("ID_Einst_SilenceTimer_10"),
				timeOfDay2("ID_Einst_SilenceTimer_11"),
				timeOfDay2("ID_Einst_SilenceTimer_12"),
				timeOfDay2("ID_Einst_SilenceTimer_13"),
				timeOfDay2("ID_Einst_SilenceTimer_14"),
				timeOfDay2("ID_Einst_SilenceTimer_15"),
				timeOfDay2("ID_Einst_SilenceTimer_16"),
				timeOfDay2("ID_Einst_SilenceTimer_17"),
				timeOfDay2("ID_Einst_SilenceTimer_18"),
				timeOfDay2("ID_Einst_SilenceTimer_19"),
				timeOfDay2("ID_Einst_SilenceTimer_20"),
				unknown("Unknown_Parameter_1114"),
				unknown("Unknown_Parameter_1115"),
				unknown("Unknown_Parameter_1116"),
				unknown("Unknown_Parameter_1117"),
				unknown("Unknown_Parameter_1118"),
				unknown("Unknown_Parameter_1119"),
				unknown("Unknown_Parameter_1120"),
				unknown("Unknown_Parameter_1121"),
				unknown("Unknown_Parameter_1122"),
				unknown("Unknown_Parameter_1123"),
				unknown("Unknown_Parameter_1124"),
				unknown("Unknown_Parameter_1125"),
				unknown("Unknown_Parameter_1126"),
				unknown("Unknown_Parameter_1127"),
				unknown("Unknown_Parameter_1128"),
				unknown("Unknown_Parameter_1129"),
				unknown("Unknown_Parameter_1130"),
				unknown("Unknown_Parameter_1131"),
				unknown("Unknown_Parameter_1132"),
				unknown("Unknown_Parameter_1133"),
				unknown("Unknown_Parameter_1134"),
				unknown("Unknown_Parameter_1135"),
				unknown("Unknown_Parameter_1136"),
				unknown("Unknown_Parameter_1137"),
				unknown("Unknown_Parameter_1138"),
				unknown("Unknown_Parameter_1139"),
				unknown("Unknown_Parameter_1140"),
				unknown("Unknown_Parameter_1141"),
				unknown("Unknown_Parameter_1142"),
				unknown("Unknown_Parameter_1143"),
				unknown("Unknown_Parameter_1144"),
				unknown("Unknown_Parameter_1145"),
				unknown("Unknown_Parameter_1146"),
				unknown("Unknown_Parameter_1147"),
				unknown("Unknown_Parameter_1148"),
				unknown("Unknown_Parameter_1149"),
				unknown("Unknown_Parameter_1150"),
				unknown("Unknown_Parameter_1151"),
				unknown("Unknown_Parameter_1152")
		));
	}
}
